export const state = {
	domCache: {},
	translations: {
		en: {
			language_name: "English",
			title: "Dolby Tuning DIY",
			load_config: "Load Config",
			save_config: "Save Config",
			apply_tuning: "Apply Tuning",
			reset_to_default: "Reset to default values",
			language: "Language:",
			simple_mode: "Simple Mode",
			expert_mode: "Expert Mode",
			action_log: "Action Log",
			no_output: "No output from script",
			media_intelligence: "Dolby Media Intelligence",
			dolbymidvlev: "mi-Volume Leveler",
			dolbymiieq: "mi-IEQ Steering",
			dolbymisurcomp: "mi-Surround Compressor Steerer",
			dolbymiadaptvirt: "mi-Adaptive Virtualizer",
			dolbymivirtbin: "mi-Virtualizer Binaural Steering",
			dolbymidialenh: "mi-Dialog Enhancer Steering",
			headphone_tuning: "Headphone Tuning",
			speaker_tuning: "Speaker Tuning",
			enabled: "Enabled:",
			intelligent_eq: "Intelligent EQ",
			load_base: "Load Base Template:",
			select_placeholder: "-- Select --",
			reset_template: "Reset to Template",
			preset: "Preset:",
			balanced: "Balanced",
			detailed: "Detailed",
			warm: "Warm",
			no_ieq: "No IEQ",
			strength: "Strength:",
			bass_boost: "Bass Boost",
			bass_enhancer_boost: "Bass Enhancer Boost:",
			bass_toggle: "VirtualBass <-> BassEnhancer Toggle",
			mode: "Mode:",
			custom_eq_loaded: "Custom EQ values loaded",
			resetting_custom_eq: "Custom EQ values has been reset",
			sliders_shrunk: "Sliders shrunk by",
			sliders_expand: "Expand Sliders by",
			sliders_expanded: "Sliders expanded by",
			custom_reset: "Custom equalizer reset to default",
			slider_height_min: "Slider height reached minimum",
			slider_height_max: "Slider height reached maximum",
			flat: "Flat",
			bass_emphasis: "Bass Emphasis",
			treble_emphasis: "Treble Emphasis",
			vocal_clarity: "Vocal Clarity",
			pop_rock: "Pop/Rock",
			electro_dance: "Electro/Dance",
			edm: "EDM",
			drum_bass: "Drum & Bass",
			classical_acoustic: "Classical/Acoustic",
			metal: "Metal",
			reggae: "Reggae",
			loudness: "Loudness",
			custom: "Custom",
			freq_47: "47 Hz",
			freq_141: "141 Hz",
			freq_234: "234 Hz",
			freq_328: "328 Hz",
			freq_469: "469 Hz",
			freq_656: "656 Hz",
			freq_844: "844 Hz",
			freq_1031: "1031 Hz",
			freq_1313: "1313 Hz",
			freq_1688: "1688 Hz",
			freq_2250: "2250 Hz",
			freq_3000: "3000 Hz",
			freq_3750: "3750 Hz",
			freq_4688: "4688 Hz",
			freq_5813: "5813 Hz",
			freq_7125: "7125 Hz",
			freq_9000: "9000 Hz",
			freq_11250: "11250 Hz",
			freq_13875: "13875 Hz",
			freq_19688: "19688 Hz",
			vb_unsupported: "VB is unsupported, using BE (Bass Enhancer)",
			error_checking_vb_support: "Error checking Virtual Bass support",
			feature_unsupported: "This feature is not supported on your device",
			bass_cutoff: "Bass Cutoff:",
			bass_width: "Bass Width:",
			harmonics_type: "Harmonics Type:",
			first_harmonic: "First Harmonic",
			more_harmonics: "More Harmonics",
			extra_harmonics: "Extra Harmonics",
			min_mix_frequency: "Min MIX Frequency",
			max_mix_frequency: "Max MIX Frequency",
			min_source_frequency: "Min SRC Frequency",
			max_source_frequency: "Max SRC Frequency",
			harmonics_boost: "Harmonics Boost:",
			linear_gain: "Linear Gain:",
			headphone_volume_booster: "Headphone Volume Booster",
			headphone_volume_balancer: "Headphone Volume Balancer",
			boost_in_db: "Boost in dB:",
			dialog_enhancer: "Dialog Enhancer",
			off: "0 - Off",
			movie_profile_only: "1 - Movie Profile Only",
			all_profiles: "2 - All Profiles",
			ducking: "Ducking:",
			virtualizer: "Virtualizer",
			source_distance: "Source Distance:",
			surround_boost: "Surround Boost:",
			left_right_angle: "Left-Right Angle:",
			center_oriented: "1 - Center Oriented",
			expanded: "2 - Expanded",
			height_filter: "Height Filter",
			slightly_elevated: "Slightly Elevated",
			more_elevated: "More Elevated",
			advanced_renderer: "Advanced Renderer:",
			stock: "Stock",
			option_1: "Option 1",
			option_2: "Option 2",
			motorola_spatializer: "Motorola Spatializer",
			xiaomi_15_spatializer: "Xiaomi 15 Spatializer",
			ShadoV_favorite_1: "ShadoV Favorite 1",
			ShadoV_favorite_2: "ShadoV Favorite 2",
			ShadoV_favorite_3: "ShadoV Favorite 3",
			volume_leveler: "Volume Leveler",
			reaction_speed: "Reaction Speed:",
			peak_attenuation: "Peak Attenuation:",
			signal_mod: "Signal Mod:",
			regulator: "Regulator",
			timbre_preservation: "Timbre Preservation:",
			regulator_overdrive: "Regulator Overdrive:",
			level_1: "1",
			level_2: "2",
			level_3: "3",
			level_4: "4",
			speaker_volume_booster: "Speaker Volume Booster",
			volume_boost_in_db: "Vol Boost in dB:",
			output: "Output",
			default: "Default",
			yes: "YES",
			no: "NO",
			on: "ON",
			off: "OFF",
			numerals: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
			translations_loaded: "Translations loaded successfully",
			language_switched_to: "Language switched to",
			switched_to: "Switched to",
			headphone_bass_render_method_set_to: "Headphone bass render method set to",
			speaker_bass_render_method_set_to: "Speaker bass render method set to",
			virtual_bass: "Virtual Bass",
			bass_enhancer: "Bass Enhancer",
			config_loaded: "Configuration loaded successfully",
			error_loading_config: "Error loading configuration",
			config_saved: "Configuration saved successfully",
			error_saving_config: "Error saving configuration",
			applying_tuning: "Applying tuning...",
			applying_tuning_time_warning: "Please wait 30-60 seconds",
			action_already_running: "Action already running, please wait",
			tuning_applied: "Tuning applied successfully",
			error_applying_tuning: "Error applying tuning",
			updated_headphone_custom_values_to: "Updated headphone custom values to",
			updated_speaker_custom_values_to: "Updated speaker custom values to",
			htunedrate: "Tuned Samplerate",
			stunedrate: "Tuned Samplerate",
			samplerate_44100: "44100 Hz",
			samplerate_48000: "48000 Hz",
			samplerate_88200: "88200 Hz",
			samplerate_96000: "96000 Hz",
			samplerate_176400: "176400 Hz",
			samplerate_192000: "192000 Hz",
			samplerate_352800: "352800 Hz",
			samplerate_384000: "384000 Hz",
			h_output_channels: "Channel Count",
			s_output_channels: "Channel Count"
		}
	},
	supportedFeatures: {
		harm: false,
		angle: false,
		distance: false,
		hadvancedvirt: false,
		sadvancedvirt: false,
		hvirtmode: false,
		svirtmode: false
	},
	currentConfig: {},
	customValues: '103,32568,11164,5090,0,3,3,3',
	scustomValues: '103,32568,11164,5090,0,3,3,3',
	heqCustomValues: '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0',
	seqCustomValues: '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0',
	hieqCustomValues: '150,142,188,216,189,195,202,199,210,225,230,236,235,235,214,165,112,49,-24,-217',
	sieqCustomValues: '150,142,188,216,189,195,202,199,210,225,230,236,235,235,214,165,112,49,-24,-217',
	actionRunning: false,
	isSimpleMode: true
};